### ISSUE TITLE
Support for ISNULL built in function

### ISSUE THREAD

**Issue by MarkEwer** [rkoeninger/PocketSql#3]
In one of the queries, I am trying to unit test I have an `ISNULL(expression, default)` statement in the select list. However, it seems that this function is not yet implemented.

Any changes this can get added?  Or, can you drop in some documentation on how your function parsing works so I can implement it and submit a PR?

**Comment by rkoeninger** [comment]
I didn't get around to fleshing out standard functions. You can see in [Eval.FunctionCall.cs](https://github.com/rkoeninger/PocketSql/blob/3634a66344f35a607117e4dccf5ea72f5f806eea/PocketSql.Lib/Evaluation/Eval.FunctionCall.cs) that it just has a couple of switch statements that check for specific function names. `"isnull"` could be supported by adding it to these.

It would only make sense to add it to `UngroupedFunctionCall` right? What would `ISNULL` mean if applied to a grouped column?

(Actually, I'm realizing that the way this is written, it distinguishes if we're in a query with `GROUP BY` and not if the argument references a column specified in the `GROUP BY` clause which is of course not the same thing.) Does your query containing `ISNULL` also use `GROUP BY`?

**Comment by MarkEwer** [comment]
Thanks for the quick response!

no, it does not have a group by. I have something like this:

```
Select <some columns>,
           ISNULL(preferredFirstName, firstName) as 'FirstName',
           <other columns>
From <employeesTable>
```

This way I show the employee's preferred or nick-name if they have one.

**Comment by MarkEwer** [comment]
As a workaround, I was able to change the query to read `IIF(ei.preferredFirstName is null, ei.firstName, ei.preferredFirstName)` and this did work with PocketSQL.

**Comment by rkoeninger** [comment]
`ISNULL` added in https://github.com/rkoeninger/PocketSql/commit/546539ffc94e4b7b80324b774b34b625079a2f4e

**Comment by MarkEwer** [comment]
Dude, you're awesome!On Nov 9, 2019 3:38 AM, Robert Koeninger <notifications@github.com> wrote:ISNULL added in 546539f
