### ISSUE TITLE
Support for NULLIF() function

### ISSUE THREAD

**Issue by MarkEwer** [rkoeninger/PocketSql#4]
In one of the queries, I am trying to unit test I have a `NULLIF(expression, value)` statement in the select list. However, it seems that this function is not yet implemented.

Any changes this can get added? Or, can you drop in some documentation on how your function parsing works so I can implement it and submit a PR?

**Comment by rkoeninger** [comment]
The answer to this one is the same as #3 . I'll look at implementing it.

**Comment by rkoeninger** [comment]
Added in https://github.com/rkoeninger/PocketSql/commit/756760d056925b0a9f2be1743d547f8a928e53d4
