### ISSUE TITLE
Supporting .NET Core

### ISSUE THREAD

**Issue by rkoeninger** [rkoeninger/PocketSql#5]
@MarkEwer Since you're the only one using this library right now - would you be caused any difficulty by me moving it to .NET Standard so it can be used by .NET Framework and .NET Core? I don't think it will be a problem but thought I'd ask my user first.

**Comment by MarkEwer** [comment]
That's a fantastic idea! I love it.

**Comment by rkoeninger** [comment]
Question I should have asked first was: Is the T-SQL parser .net framework only? And it is.

Maybe it can be forked and refactored to support .net standard but putting this on the back burner.

**Comment by MarkEwer** [comment]
Lol. I could help you out with that if you can point me in the right direction.

**Comment by MarkEwer** [comment]
Looks like Microsoft may have moved the T-SQL parser into the assembly called DacFx.  I'll try to update the references to this assembly and see if all the unit tests still pass.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.transactsql.scriptdom?view=sql-dacfx-140.3881.1

**Comment by MarkEwer** [comment]
Good News! I did a quick experiment changing out the package reference from the `scriptdom` library to the `DacFx` package and all the unit tests still pass! I'll try moving to netstandard 2.0 for you soon.

https://www.nuget.org/packages/Microsoft.SqlServer.DACFx/

**Comment by rkoeninger** [comment]
Yeah, I saw that and I didn't see DACFx have .net standard support. I'm currently experimenting with de-compiling and re-compiling the ScriptDom dll targeting .net standard with a different csproj.

**Comment by rkoeninger** [comment]
With #8 merged, all dependencies now fit into .netstandard 2.0. I'm going to start working on making the library itself target .netstandard 2.0 and the demo target .net core.
