### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by MarkEwer** [rkoeninger/PocketSql#9]
I suggest that we create a Nuget package for this project.  What do you think?

**Comment by rkoeninger** [comment]
Certainly. I'm going to do the .net core transition first. I've been lazy but will try to do both this week.

**Comment by MarkEwer** [comment]
+1

**Comment by rkoeninger** [comment]
@MarkEwer give the nuget package a try with your project and please open a new issue if there's a problem.

https://www.nuget.org/packages/PocketSql

**Comment by MarkEwer** [comment]
sorry for the delay … yes, this worked perfectly. I had to upgrade our Team City build agents and our web farm from .Net 4.5.2 but now that I have done that all is good.
